version: '3'
services:
  local-rag:
    container_name: local-rag
    image: hududed/mm-rag
    restart: unless-stopped
    environment:
      - TZ=America/Denver
    ports:
      - '8501:8501/tcp'
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
